"""Report Compiler - builds final markdown report."""

from src.agents.base import BaseAgent


class ReportCompilerAgent(BaseAgent):
    async def run(self, state: dict) -> dict:
        self.log_start(state)
        topic = state["topic"]
        research = "\n".join(state.get("research_notes", []))
        role_desc = state.get("role_description", "No role generated")
        benefits = ", ".join(state.get("recommended_benefits", []))

        report = f"""# HR Innovation Report: {topic}

## Research Summary
{research}

## Designed Role
{role_desc}

## Recommended Benefits
{benefits}

---
*Generated by HR Multi-Agent System*
"""
        result = {"final_report": report}
        self.log_end(result)
        return result
